---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: log2ram
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:${TAG:-latest}"
    cgroupns_mode: host
    command: ${DOCKER_COMMAND:-""}
    override_command: false
    privileged: true
    pre_build_image: true
    user: 0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    prepare: "../default/converge.yml"
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
