---
- name: Install log2ram.
  ansible.builtin.include_tasks: "{{ item }}"
  vars:
    files:
      - installation.yml
  loop: "{{ q('first_found', files, errors='ignore') }}"
  when: log2ram_state == "install"

- name: Check if log2ram is installed (Non-Debian systems).
  ansible.builtin.stat:
    path: /usr/local/bin/log2ram
  register: log2ram_is_installed

- name: Set fact about installed packages in Non-Debian.
  ansible.builtin.set_fact:
    log2ram_installed: "{{ 'true' if log2ram_is_installed.stat['path'] is defined else 'false' }}"

- name: Configure log2ram.
  ansible.builtin.include_tasks: configuration.yml
  when:
    - log2ram_installed | bool
    - not log2ram_state == "remove"

- name: Ensure log2ram is started and enabled on boot.
  ansible.builtin.service:
    name: log2ram
    state: started
    enabled: true
  when:
    - log2ram_installed | bool
    - not log2ram_state == "remove"

- name: Assert
  ansible.builtin.assert:
    that:
      - log2ram_installed | bool
    fail_msg: "log2ram installation failed!"
    success_msg: "log2ram installation was successful."
  when: log2ram_state == "install"

- name: Gather service facts.
  ansible.builtin.service_facts:

- name: Uninstall log2ram.
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - log2ram_state == "remove"
    - log2ram_installed | bool

- name: Update log2ram.
  ansible.builtin.include_tasks: update.yml
  when:
    - log2ram_state == "update"
    - log2ram_installed | bool
